
[general]
	#The material blacklist of this module.
	materialBlacklist = []

[recipes]
	#The materials that should not have plate press to plate recipes added.
	toPlateMaterialBlacklist = []

