
[general]
	#The material blacklist of this module.
	materialBlacklist = []

[recipes]
	#The materials that should not have macerator to dirty dust recipes added.
	toDirtyDustMaterialBlacklist = []

