
#Configurations for material Cinnabar.
[general]
	#The alternative names of this material.
	alternativeNames = []
	#The byproducts of this material.
	extras = []
	#Is the storage block of this material small (2x2).
	isSmallStorageBlock = false
	#The module blacklist of this material.
	moduleBlacklist = []
	#Should items of this material have the enchanted glow.
	hasEffect = false
	#The model type of the material.
	modelType = "crystal"
	#The color of this material.
	color = 11623767

[molten]
	#The temperature of this molten fluid.
	temperature = 1000

[enderio]
	#The default byproduct material to output in Ender IO's sagmill.
	byproduct = "minecraft:cobblestone"

[mekanism]
	#The default base to use in Mekanism's Combiner to recreate ores.
	oreBase = "minecraft:cobblestone"

