#TODO: Provide instructions for modpack devs.
---
ModPackConfigName: "BBOP-Extended"
ModPackConfigVersion: 10
ShowOTGWorldCreationMenu: true
version: 1
WorldName: "BBOP-Extended"
Overworld:
  PresetName: "BBOP-Extended"
  DimensionId: 0
  ShowInWorldCreationGUI: true
  LowestSupportedModPackConfigVersion: 0
  RemoveOnUpdate: false
  Seed: ""
  GameType: "Survival"
  BonusChest: false
  AllowCheats: true
  WorldBorderRadiusInChunks: 0
  PregeneratorRadiusInChunks: 0
  Settings:
    DimensionPortalMaterials:
    - "DIRT"
    PortalColor: "default"
    PortalParticleType: "portal"
    PortalMobType: "zombie_pigman"
    PortalMobSpawnChance: 2000
    IsOTGPlus: false
    DimensionBelow: ""
    DimensionAbove: ""
    DimensionBelowHeight: 0
    DimensionAboveHeight: 342
    TeleportToSpawnOnly: false
    WelcomeMessage: ""
    DepartMessage: ""
    HasSkyLight: true
    IsSurfaceWorld: true
    CanRespawnHere: true
    DoesWaterVaporize: false
    DoesXZShowFog: false
    UseCustomFogColor: false
    FogColorRed: 0.20000000298023224
    FogColorGreen: 0.029999999329447746
    FogColorBlue: 0.029999999329447746
    IsSkyColored: true
    CloudHeight: 128
    CanDoLightning: true
    CanDoRainSnowIce: true
    IsNightWorld: false
    VoidFogYFactor: 0.03125
    GravityFactor: 0.08
    ShouldMapSpin: false
    CanDropChunk: true
    RespawnDimension: 0
    MovementFactor: 1
    ItemsToAddOnJoinDimension: ""
    ItemsToRemoveOnJoinDimension: ""
    ItemsToAddOnLeaveDimension: ""
    ItemsToRemoveOnLeaveDimension: ""
    ItemsToAddOnRespawn: ""
    SpawnPointSet: false
    SpawnPointX: 52
    SpawnPointY: 65
    SpawnPointZ: 2048
    PlayersCanBreakBlocks: true
    ExplosionsCanBreakBlocks: true
    PlayersCanPlaceBlocks: true
  GameRules:
    CommandBlockOutput: true
    DisableElytraMovementCheck: false
    DoDaylightCycle: true
    DoEntityDrops: true
    DoFireTick: true
    DoLimitedCrafting: false
    DoMobLoot: true
    DoMobSpawning: true
    DoTileDrops: true
    DoWeatherCycle: true
    GameLoopFunction: true
    KeepInventory: false
    LogAdminCommands: true
    MaxCommandChainLength: 65536
    MaxEntityCramming: 24
    MobGriefing: true
    NaturalRegeneration: true
    RandomTickSpeed: 3
    ReducedDebugInfo: false
    SendCommandFeedback: true
    ShowDeathMessages: true
    SpawnRadius: 10
    SpectatorsGenerateChunks: true
Dimensions:
- PresetName: "Void"
  DimensionId: 3
  ShowInWorldCreationGUI: false
  LowestSupportedModPackConfigVersion: 999
  RemoveOnUpdate: true
  Seed: ""
  GameType: "Survival"
  BonusChest: false
  AllowCheats: false
  WorldBorderRadiusInChunks: 0
  PregeneratorRadiusInChunks: 0
  Settings:
    DimensionPortalMaterials:
    - "PRISMARINE:2"
    PortalColor: "beige"
    PortalParticleType: "portal"
    PortalMobType: "zombie_pigman"
    PortalMobSpawnChance: 2000
    IsOTGPlus: false
    DimensionBelow: ""
    DimensionAbove: ""
    DimensionBelowHeight: -50
    DimensionAboveHeight: 256
    TeleportToSpawnOnly: false
    WelcomeMessage: ""
    DepartMessage: ""
    HasSkyLight: true
    IsSurfaceWorld: true
    CanRespawnHere: true
    DoesWaterVaporize: false
    DoesXZShowFog: false
    UseCustomFogColor: false
    FogColorRed: 0.20000000298023224
    FogColorGreen: 0.029999999329447746
    FogColorBlue: 0.029999999329447746
    IsSkyColored: true
    CloudHeight: 16
    CanDoLightning: true
    CanDoRainSnowIce: true
    IsNightWorld: false
    VoidFogYFactor: 0.03125
    GravityFactor: 0.08
    ShouldMapSpin: true
    CanDropChunk: true
    RespawnDimension: 0
    MovementFactor: 1
    ItemsToAddOnJoinDimension: ""
    ItemsToRemoveOnJoinDimension: ""
    ItemsToAddOnLeaveDimension: ""
    ItemsToRemoveOnLeaveDimension: ""
    ItemsToAddOnRespawn: ""
    SpawnPointSet: false
    SpawnPointX: 671
    SpawnPointY: 1
    SpawnPointZ: 2303
    PlayersCanBreakBlocks: true
    ExplosionsCanBreakBlocks: true
    PlayersCanPlaceBlocks: true
  GameRules:
    CommandBlockOutput: true
    DisableElytraMovementCheck: false
    DoDaylightCycle: true
    DoEntityDrops: true
    DoFireTick: true
    DoLimitedCrafting: false
    DoMobLoot: true
    DoMobSpawning: true
    DoTileDrops: true
    DoWeatherCycle: true
    GameLoopFunction: true
    KeepInventory: false
    LogAdminCommands: true
    MaxCommandChainLength: 65536
    MaxEntityCramming: 24
    MobGriefing: true
    NaturalRegeneration: true
    RandomTickSpeed: 3
    ReducedDebugInfo: false
    SendCommandFeedback: true
    ShowDeathMessages: true
    SpawnRadius: 1
    SpectatorsGenerateChunks: true
- PresetName: "AlienJungle"
  DimensionId: 200
  ShowInWorldCreationGUI: false
  LowestSupportedModPackConfigVersion: 0
  RemoveOnUpdate: false
  Seed: ""
  GameType: "Survival"
  BonusChest: false
  AllowCheats: false
  WorldBorderRadiusInChunks: 0
  PregeneratorRadiusInChunks: 0
  Settings:
    IsOTGPlus: true
    DimensionBelow: ""
    DimensionAbove: ""
    DimensionBelowHeight: 0
    DimensionAboveHeight: 256
    TeleportToSpawnOnly: false
    WelcomeMessage: ""
    DepartMessage: ""
    HasSkyLight: false
    IsSurfaceWorld: true
    CanRespawnHere: true
    DoesWaterVaporize: false
    DoesXZShowFog: true
    UseCustomFogColor: false
    FogColorRed: 0.20000000298023224
    FogColorGreen: 0.029999999329447746
    FogColorBlue: 0.029999999329447746
    IsSkyColored: true
    CloudHeight: 250
    CanDoLightning: true
    CanDoRainSnowIce: true
    IsNightWorld: true
    VoidFogYFactor: 0.03125
    GravityFactor: 0.08
    ShouldMapSpin: true
    CanDropChunk: true
    RespawnDimension: 0
    MovementFactor: 1
    ItemsToAddOnJoinDimension: ""
    ItemsToRemoveOnJoinDimension: ""
    ItemsToAddOnLeaveDimension: ""
    ItemsToRemoveOnLeaveDimension: ""
    ItemsToAddOnRespawn: ""
    SpawnPointSet: false
    SpawnPointX: 1812
    SpawnPointY: 1
    SpawnPointZ: 2028
    PlayersCanBreakBlocks: true
    ExplosionsCanBreakBlocks: true
    PlayersCanPlaceBlocks: true
  GameRules:
    CommandBlockOutput: true
    DisableElytraMovementCheck: false
    DoDaylightCycle: true
    DoEntityDrops: true
    DoFireTick: true
    DoLimitedCrafting: false
    DoMobLoot: true
    DoMobSpawning: true
    DoTileDrops: true
    DoWeatherCycle: true
    GameLoopFunction: true
    KeepInventory: false
    LogAdminCommands: true
    MaxCommandChainLength: 65536
    MaxEntityCramming: 24
    MobGriefing: true
    NaturalRegeneration: true
    RandomTickSpeed: 3
    ReducedDebugInfo: false
    SendCommandFeedback: true
    ShowDeathMessages: true
    SpawnRadius: 1
    SpectatorsGenerateChunks: true
    