name: Publishing on CurseForge
on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  cf-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: release
        uses: gregziegan/fetch-latest-release@v2.0.0

      - name: ğŸ“ƒ Save changelog content to file
        uses: DamianReeves/write-file-action@master
        with:
          path: latest.md
          contents: ${{ steps.release.outputs.body }}
          write-mode: overwrite

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: ğŸ–¼ï¸ Generate image from md
        run: npx mdimg -i latest.md -o latest.png -w 800 --css githubDark

      - name: ğŸ–¼ï¸ â¡ï¸ Send discord message
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          file: "./latest.png"
          message: >
            ğŸš€ New release: __**{{ steps.release.outputs.tag_name }}**__ {{ steps.release.outputs.name }}
            {{ steps.release.outputs.url }}

      - run: npm i --omit=dev

      - name: ğŸ“‹ Generate html instead of markdown
        run: node dev/lib/curseforge-md-to-html.js latest.md

      - name: ğŸ“‹ Get content of changelog html
        id: latest_html
        uses: andstor/file-reader-action@v1
        with:
          path: "latest.html"

      - name: ğŸ’½ Download .zip files from latest release
        uses: robinraju/release-downloader@v1.4
        with:
          latest: true
          fileName: "*.zip"

      - name: "ğŸ’» Upload Client"
        uses: itsmeow/curseforge-upload@v3
        id: client
        with:
          release_type: release
          display_name: "E2E-Extended-${{ steps.release.outputs.tag_name }}"
          file_path: "E2E-Extended-${{ steps.release.outputs.tag_name }}.zip"
          game_endpoint: "minecraft"
          game_versions: "Minecraft 1.12:1.12.2"
          project_id: "561105"
          token: "${{ secrets.CURSEFORGE_API_TOKEN }}"
          changelog_type: html
          changelog: "${{ steps.latest_html.outputs.contents }}"

      - name: "ğŸ–¥ï¸ Upload Server"
        uses: itsmeow/curseforge-upload@v3
        with:
          release_type: release
          display_name: "E2E-Extended-${{ steps.release.outputs.tag_name }}-server"
          file_path: "E2E-Extended-${{ steps.release.outputs.tag_name }}-server.zip"
          game_endpoint: "minecraft"
          project_id: "561105"
          parent_file_id: ${{ steps.client.outputs.id }}
          token: "${{ secrets.CURSEFORGE_API_TOKEN }}"